### ISSUE TITLE
Cannot find module mean-postinstall à l'installation

### ISSUE THREAD

**Issue by snroki** [eleven-labs/WilsonPicture#7]
A l'installation (npm install && bower install):

```
Error: Cannot find module 'c:\wamp\www\WilsonPicture\node_modules\meanio\node_modules\mean-cli\bin\mean-postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! mean@0.4.3 postinstall: `node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mean@0.4.3 postinstall script.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall

npm ERR! You can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\wamp\www\WilsonPicture
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\wamp\www\WilsonPicture\npm-debug.log
npm ERR! not ok code 0
```

Une idée ?

**Comment by Pouzor** [comment]
Corrigé dans le dernier commit. Git pull et tu relance npm install
